### ISSUE TITLE
exec: foreman: not found

### ISSUE THREAD

**Issue by demenzio** [tiredofit/docker-staytus#1]
After running the container, the docker log is showing the following error:

** [staytus] Starting Foreman
./run: line 58: exec: foreman: not found

**Comment by tiredofit** [comment]
Hi there, Looks like there has been something that has changed when it pulls the dependencies building the app. Give me a day or so to test - we have yet to encounter this in production.

**Comment by zul-jin** [comment]
I encountered the same issue after I ran the container today. Is there a known fix for it by now?

**Comment by ghost** [comment]
@tiredofit I encountered the same issue after I ran the container today. Is there a known fix for it by now?

**Comment by tiredofit** [comment]
Hi there, sorry, I had forgotten about this entirely. I've just revamped the image and made appropriate changes to make this image function again. It is being pushed to Docker Hub as we speak, however I recommend noting that instead of port `5000` listening it is now `8787`.

**Comment by tiredofit** [comment]
https://github.com/tiredofit/docker-staytus/releases/tag/2.4
